### ISSUE TITLE
resp.ToUpperCase is not a function in v0.2.5

### ISSUE THREAD

**Issue by ngrie** [sy1vain/node-pjlink#14]
The MR #13 that was merged a few days ago introduced an error:

```
/path/to/my/project/node_modules/pjlink/lib/command.js:30
	resp = resp.ToUpperCase();
	            ^

TypeError: resp.ToUpperCase is not a function
    at Command.PowerCommand.Command.handleResponse (/path/to/my/project/node_modules/pjlink/lib/command.js:30:14)
    at PJLink._handleResponse (/path/to/my/project/node_modules/pjlink/lib/pjlink.js:286:14)
    at PJLink._onError (/path/to/my/project/node_modules/pjlink/lib/pjlink.js:215:7)
```

Looking at the code it is pretty obvious that the added code cannot work as it is calling a function that does not exist.

**Comment by sy1vain** [comment]
Yes you are right. I merged a pull request but am not actively developing (and don’t have the correct hardware). I should have checked the pull request better. Will changing it to toUpperCase() resolve the issue?

**Comment by ngrie** [comment]
`resp` is a [Response](https://github.com/sy1vain/node-pjlink/blob/master/lib/response.js) instance, i don't see why calling `toUpperCase()` on it should work.

The intention of the MR probably was to transform the `cmd` part of the response, but I don't know for sure.

**Comment by sy1vain** [comment]
Yes, I think so, but I did not check it properly. I assumed it was tested as least. I am not actively maintaining this code. I will have a look to try and fix this.

**Comment by sy1vain** [comment]
I pushed a change, can you verify that this does not break? I have no hardware to test at the moment.

**Comment by ngrie** [comment]
[There are cases](https://github.com/sy1vain/node-pjlink/blob/master/lib/pjlink.js#L215) where a Response is initialized with `null` as the first argument. The `toUpperCase()` call you introduced breaks there as well.

**Comment by sy1vain** [comment]
I reverted all these changes. To issue the #13 tried to solve was already solved in an earlier version and the proposed solution there was not checked by the autor (and by me, my bad).
