### ISSUE TITLE
Plans to include this in npm ?

### ISSUE THREAD

**Issue by natcl** [sy1vain/node-pjlink#2]
Hello,
Would be great if this was available on npm !
I plan on writing a Node-red module based on this and it would simplify things a lot !

Thanks !

**Comment by sy1vain** [comment]
`npm install pjlink` ;-)

**Comment by natcl** [comment]
Nice thanks !
This will make a very nice node-red module ! :)

**Comment by natcl** [comment]
Hey thanks again for the updates !
Here's the Node-Red package:
https://www.npmjs.com/package/node-red-contrib-pjlink
