### ISSUE TITLE
Connection timeout

### ISSUE THREAD

**Issue by natcl** [sy1vain/node-pjlink#3]
Hello,
I've been testing this library with Node-Red and I have some issues.  It seems like it disconnects at random.  Once disconnected, it gives a Connection timeout error and I have to restart node to reconnect.

I also tried from the command line directly and I get the same result.  After a while of calling a method (say getName) I get a connection timeout.

Any ideas ?

Thanks !

**Comment by natcl** [comment]
Just a small update, I also tested this against the test program linked in the Readme and get the same timeouts after a while...

**Comment by sy1vain** [comment]
Most pjlink devices close the connection after about 30 seconds of inactivity. At what interval are you polling data? And is the device on the local network?

In my (very specific) case I was polling quite often. And after a disconnect it would eventually reconnect. But it might depend on how the connection is closed.

In theory it should handle the disconnect internally and reconnect on the next command that you send after that.

**Comment by natcl** [comment]
Hello,
I did my tests on the same subnet, both with a real projector and the test app.  I was calling getName, getManufacturer at about 1 second intervals.  After a while (maybe 1 minute or 2, seems random) It would return a connection timeout error.  After that, it would not reconnect unless I quit node and restart.

**Comment by sy1vain** [comment]
I just did some quick testing and ran into a similar problem.

Can you try setting the timeout to by adding that to your settings object that you pass to pjlink. This might already get rid of the timeouts.

I also noticed a problem with not terminating the connection properly, this might be the reason why you need to restart node. I will try to look into to this over the weekend.

**Comment by natcl** [comment]
Thanks for checking this !
I'm not sure what I should set the timeout to ?

**Comment by natcl** [comment]
(I assume you meant 0 as I tested and it seems to have solved the problem)

**Comment by sy1vain** [comment]
Yes I meant 0, typing on the run..

**Comment by natcl** [comment]
Thanks, solved the timeout issue !
Only problem remaining is that from within node red, if redeploy the
instance it stops communicating.  I have to restart node-red completely to
make it work again, I assume it's linked to the way the disconnection is
handled.

2015-02-05 11:00 GMT-05:00 sy1vain <notifications@github.com>:

**Comment by sy1vain** [comment]
I set the default timeout to 0 to make it more clear & prevent timeout issues.

When they do occur, the current connection is closed completely so it will reconnect on next message.

You can now also create a new instance as long you call 'disconnect()' on the old instance. Apparently the behaviour of node sockets changed a little since I created this initially, so you need to call this otherwise it keeps the connection open.

**Comment by natcl** [comment]
Thanks a lot !
