### ISSUE TITLE
open multiple connections

### ISSUE THREAD

**Issue by scharc** [sy1vain/node-pjlink#4]
I am trying to use the pjlink to speak to at least 60 different projectors. I can connect to one, talk with it and then close the connection with disconnect().

problem is, that I cant talk to more the one at the same time. Do you have any suggestions or hints how to get this working?

at the moment I use recursion to work around the problem, but that takes forever to get every status

**Comment by sy1vain** [comment]
As stated in the PJLink protocol, you need to create multiple connections to use multiple projectors. Unfortunately.

I haven't tried this, but you could try to create an Array with all the PJLink connections and use an async library to call the status of all projectors in parallel.  But maybe you tried this already.

PS There should be no need to disconnect between calls. It should auto connect if it should have lost the connection. It is closed automatically by the PJLink protocol if implemented correctly. Sending commands at a certain interval should keep the connection open.

**Comment by paco3346** [comment]
There's also a bug where all instances are sharing the netSocket because of how the prototypes are set up. I'll put in a PR soon in the next few days to address this.

@scharc Feel free to hit me up if you'd like help implementing @sy1vain's idea.

**Comment by sy1vain** [comment]
Ah, good to know. I used it in a single setup when developing this. Great if you have a fix @paco3346

**Comment by scharc** [comment]
@paco3346 any news on you side about the PR?

**Comment by sy1vain** [comment]
@paco3346 Thanks for the fix! Glad that you could find and took the time.

**Comment by paco3346** [comment]
Np @sy1vain!
I'm really amused that you thought of this today @scharc. As I was brushing my teeth this morning I wondered "are there any PRs I've been meaning to submit but haven't?". Your spidey senses must have been tingling.
